name: InstaCart-Analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  #- jupyter
  #- notebook
  #- ipykernel
  - pip
  - pip:
  #    - any-pip-only-package  # remove if unused